version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uber
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  api:
    build: ./apps/api
    command: sh -c "npm run migrate && npm run start"
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/uber?schema=public
      JWT_SECRET: dev
      REDIS_URL: redis://redis:6379
      CORS_ORIGIN: http://localhost:3000
    depends_on:
      - db
      - redis
    ports:
      - '4000:4000'
  web:
    build: ./apps/web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    depends_on:
      - api
    ports:
      - '3000:3000'
volumes:
  db_data: {}